name: test

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'
  pull_request:


env:
  BUILD_TAG: fail2ban:test
  CONTAINER_NAME: fail2ban

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build
        uses: docker/bake-action@v3
        with:
          targets: image-local
        env:
          DEFAULT_TAG: ${{ env.BUILD_TAG }}
      -
        name: Start container
        run: |
          docker rm -f ${{ env.CONTAINER_NAME }} > /dev/null 2>&1 || true
          docker run -d --name ${{ env.CONTAINER_NAME }} \
            --network host \
            --cap-add NET_ADMIN \
            --cap-add NET_RAW \
            ${{ env.BUILD_TAG }}
      -
        name: Check container logs
        uses: crazy-max/.github/.github/actions/container-logs-check@main
        with:
          container_name: ${{ env.CONTAINER_NAME }}
          log_check: "Server ready"
          timeout: 120
